# Generated by Django 5.2.11 on 2026-03-10 10:55
import uuid
from django.db import migrations, models

def add_multi_target_template(apps, schema_editor):
    User = apps.get_model('questionnaire', 'User')
    Questionnaire = apps.get_model('questionnaire', 'Questionnaire')
    Question = apps.get_model('questionnaire', 'Question')

    # 获取或创建创建者用户（使用第一个超级用户，若无则创建系统用户）
    creator = User.objects.filter(is_superuser=True).first()
    if not creator:
        creator = User.objects.create_user(
            username='template_system',
            password='!',
            is_superuser=True,
            is_staff=True,
            user_type='admin',
            is_original_admin=True,
        )
        creator.set_unusable_password()
        creator.save()

    # 创建模板问卷（使用确定性的 UUID，便于回滚时精确删除）
    template = Questionnaire.objects.create(
        id=uuid.uuid5(uuid.NAMESPACE_DNS, 'multi-target-template'),
        title='360度多目标评估模板',
        description='请依次评价所有指定目标，每个目标需回答相同问题。',
        creator=creator,
        status='draft',
        access_type='private',
        is_template=True,
        is_multi_target=True,
        targets=['张三', '李四', '王五', '赵六'],
    )

    # 添加预设问题
    questions = [
        {
            'text': '该员工的工作态度如何？',
            'question_type': 'radio',
            'order': 1,
            'required': True,
            'options': ['非常满意', '满意', '一般', '不满意', '非常不满意'],
            'max_length': 0,
        },
        {
            'text': '该员工的团队协作能力？',
            'question_type': 'radio',
            'order': 2,
            'required': True,
            'options': ['优秀', '良好', '一般', '较差'],
            'max_length': 0,
        },
        {
            'text': '请给出具体的建议或评价：',
            'question_type': 'text',
            'order': 3,
            'required': False,
            'options': [],
            'max_length': 500,
        },
    ]
    for q in questions:
        Question.objects.create(questionnaire=template, **q)

def remove_template(apps, schema_editor):
    Questionnaire = apps.get_model('questionnaire', 'Questionnaire')
    # 通过标题删除（也可用 UUID 过滤）
    Questionnaire.objects.filter(title='360度多目标评估模板').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0005_questionnaire_is_multi_target"),
    ]

    operations = [
        migrations.RunPython(add_multi_target_template, remove_template),
    ]
